'use client';
import { useEffect, useState } from 'react';
import { cancelSubscription, exportAccountData, getAccountOverview, inviteTeamMember, requestAccountDeletion, selectAccountPlan } from '@/lib/api';
import type { AccountOverview } from '@/lib/types';

const labels: Record<string,string>={messages:'Mensagens',aiTokens:'Processamento de IA',audioMinutes:'Áudio (minutos)',storageMb:'Armazenamento (MB)',contacts:'Contatos'};
export default function AccountPage(){
 const[data,setData]=useState<AccountOverview|null>(null);const[notice,setNotice]=useState('');const[name,setName]=useState('');const[email,setEmail]=useState('');
 const load=()=>getAccountOverview().then(setData).catch(e=>setNotice(e instanceof Error?e.message:'Não foi possível carregar.'));
 useEffect(()=>{void load()},[]);
 async function plan(value:'STARTER'|'PRO'|'BUSINESS'){await selectAccountPlan(value);setNotice('Solicitação registrada. O plano será ativado após a confirmação do pagamento.');await load()}
 async function invite(){try{const r=await inviteTeamMember(name,email);setNotice(`Convite criado. Link de primeiro acesso: ${r.setupLink}`);setName('');setEmail('');await load()}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível convidar.')}}
 async function exportData(){const payload=await exportAccountData();const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bella-dados.json';a.click();URL.revokeObjectURL(url)}
 async function remove(){const confirmation=window.prompt('Digite EXCLUIR MINHA CONTA para confirmar.');if(!confirmation)return;await requestAccountDeletion(confirmation);window.location.href='/login'}
 if(!data)return <main className="min-h-screen bg-slate-950 p-8 text-white">Carregando conta...</main>;
 return <main className="min-h-screen bg-slate-950 p-6 text-white"><div className="mx-auto max-w-5xl"><a href="/" className="text-sm text-slate-400">← Voltar ao painel</a><h1 className="mt-5 text-3xl font-semibold">Conta e plano</h1>{notice&&<div className="mt-5 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm">{notice}</div>}
 <section className="mt-8 rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><div><p className="text-slate-400">Plano atual</p><h2 className="mt-1 text-2xl font-semibold">{data.company.plan}</h2></div><span className="text-sm text-emerald-300">{data.company.subscriptionStatus}</span></div><div className="mt-6 grid gap-3 md:grid-cols-3">{(['STARTER','PRO','BUSINESS'] as const).map(p=><button key={p} onClick={()=>void plan(p)} className="rounded-2xl border border-slate-700 p-4 text-left hover:border-emerald-500"><strong>{p}</strong><p className="mt-1 text-xs text-slate-400">Selecionar este plano</p></button>)}</div><p className="mt-4 text-xs text-amber-200">A cobrança automática depende da conexão do provedor de pagamentos; até lá, mudanças de plano são administradas manualmente.</p></section>
 <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Uso do mês</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{Object.entries(data.usage.metrics).map(([key,v])=><div key={key}><div className="flex justify-between text-sm"><span>{labels[key]||key}</span><span>{v.used} / {v.limit}</span></div><div className="mt-2 h-2 rounded bg-slate-800"><div className="h-2 rounded bg-emerald-500" style={{width:`${Math.min(100,v.limit? v.used/v.limit*100:100)}%`}}/></div></div>)}</div></section>
 <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Equipe ({data.company.users.length}/{data.company.teamMemberLimit})</h2><div className="mt-4 space-y-2">{data.company.users.map(u=><div key={u.id} className="rounded-xl bg-slate-950 p-3 text-sm">{u.name} · {u.email}</div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input placeholder="Nome" value={name} onChange={e=>setName(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 p-3"/><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 p-3"/><button onClick={()=>void invite()} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold">Convidar</button></div></section>
 <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Privacidade e assinatura</h2><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>void exportData()} className="rounded-xl border border-slate-700 px-4 py-3">Exportar meus dados</button><button onClick={async()=>{await cancelSubscription();setNotice('Assinatura cancelada.');await load()}} className="rounded-xl border border-amber-600/50 px-4 py-3 text-amber-200">Cancelar assinatura</button><button onClick={()=>void remove()} className="rounded-xl border border-rose-600/50 px-4 py-3 text-rose-200">Excluir conta</button></div></section>
 </div></main>
}
